version: '3.8'
services:
 mysql:
   image: "mysql:8.0"
   restart: always
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: test
     MYSQL_DATABASE: firstDb
     MYSQL_PASSWORD: test